# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: trusty
# We have some shenanigans to let us cache submodules, and update changed files
# without messing up mtimes and triggering rebuilds unnecessarily. Travis checks
# out our submodules and then restores the cache over them. We move the cached
# version out of the way, check out the versions we want, rsync over only the
# differing/updated files (updating only their mtimes), and then put the fixed
# version back.
before_install:
  - if [ -e deps ]; then mv deps deps_cached; fi
  - git submodule update --init --recursive
  - rsync -rv --checksum deps/ deps_cached/
  - rm -Rf deps
  - mv deps_cached deps
  - (ls -lah deps/; ls -lah bin/; ls -lah lib/; ls -lah include/) || true
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      ls /etc/apt/sources.list.d
      sudo rm /etc/apt/sources.list.d/google-chrome.list
      sudo apt-get update
      sudo apt-get install -qq -y gcc-4.9 g++-4.9 bc rs jq samtools cmake
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
      gcc --version && g++ --version
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science
      brew tap homebrew/versions
      brew update
      brew install jq jansson coreutils md5sha1sum samtools rasqal gtk-doc bison raptor rasqal gperftools autogen gcc49
      brew link bison --force
      brew uninstall libtool
      brew install libtool
      export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH"
      export LD_LIBRARY_PATH=/usr/local/lib/
      export LIBRARY_PATH=$LD_LIBRARY_PATH
      export CFLAGS="-I/usr/local/include/"
      which g++-4.9 || (brew unlink gcc && brew install gcc49)
      mkdir -p ./bin
      ln -sf `which g++-4.9` ./bin/g++
      ln -sf `which gcc-4.9` ./bin/gcc
     fi
  - python ./configure.py
  - source ./source_me.sh
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_BRANCH_NAME" != "autodocker" ]]; then make get-deps; fi
script:
  - |
    if [[ "$TRAVIS_BRANCH_NAME" != "autodocker" ]]; then
      case "$TRAVIS_OS_NAME" in
        linux )
          make -j4 && make test && make static -j4
          ;;
        osx )
          make -j4 && make test
          ;;
      esac
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo docker build -f Dockerfile -t "vgteam/vg:$(git describe --always --tags)" .
    fi
# Cache all our dependency directories, and our lib and include
cache:
  directories:
    - deps
    - lib
    - include
    - bin
before_cache:
  - rm -f lib/libvg.*
  - rm -f include/vg.pb.h include/vg_git_version.hpp
  - rm -f bin/vg /bin/vg* bin/g++ bin/gcc
os:
  - linux
  - osx
compiler:
  - gcc

